# Generated by Django 5.0.6 on 2024-06-18 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='equipos',
            field=models.ManyToManyField(through='futbolec.CampeonatoEquipos', to='futbolec.equipofutbol'),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='campeonatos',
            field=models.ManyToManyField(through='futbolec.CampeonatoEquipos', to='futbolec.campeonato'),
        ),
        migrations.AlterField(
            model_name='campeonatoequipos',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loscampeonatos', to='futbolec.campeonato'),
        ),
        migrations.AlterField(
            model_name='campeonatoequipos',
            name='equipo_futbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loscampeonatos', to='futbolec.equipofutbol'),
        ),
    ]
